AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cadastra um novo cliente em uma determinada fila
Resources:
  createqueueclient:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: Cadastra um novo cliente em uma determinada fila
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /client
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          -
        SubnetIds:
          - 
      Environment:
        Variables:
          MAXIMUM_QTD_NAME: '128'
          MAXIMUM_QTD_TEL: '11'
      Layers:
        - '2'
